### ISSUE TITLE
Hello everyone : this issue will be about designing a good page . read the comments please

### ISSUE THREAD

**Issue by omaralam96** [ASUMobiCarG11/ASUMobiCarG11#9]
Omar Nasr : you have to make our own wiki 
Mark youssef ,Martin Joseph : create 5 new folders carrying the following names:
                                                   1)designing car
                                                   2) The code
                                                   3) Installing car step by step
                                                   4) Promos
                                                   5)Components
kareem , Fatma , Fayros : you have to make documents of our group
omar alam ,omar hesham : we have to do:
                                            *Intro page 
                                            *download every file has been uploaded till now and re-upload it on its 
                                             specific file
mikel , mario : buy the reset components .

**Comment by omaralam96** [comment]
We all can help in deleting and re-upload files again

**Comment by MichaelAshrafYacop** [comment]
what is the reset components omaralam96    .

**Comment by MichaelAshrafYacop** [comment]
and I will help you in 
download every file has been uploaded till now and re-upload it on its
specific file

**Comment by omaralam96** [comment]
i have re-uploaded my own file i hope everyone to do the same,
